config/routes.rb
Rails.application.routes.draw do
  resources :prototypes
  root 'prototypes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/prototype.rb
class Prototype < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: %i[ show edit update destroy ]

  # GET /prototypes or /prototypes.json
  def index
    @prototypes = Prototype.all
  end

  # GET /prototypes/1 or /prototypes/1.json
  def show
  end

  # GET /prototypes/new
  def new
    @prototype = Prototype.new
  end

  # GET /prototypes/1/edit
  def edit
  end

  # POST /prototypes or /prototypes.json
  def create
    @prototype = Prototype.new(prototype_params)

    respond_to do |format|
      if @prototype.save
        format.html { redirect_to prototype_url(@prototype), notice: "Prototype was successfully created." }
        format.json { render :show, status: :created, location: @prototype }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prototype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prototypes/1 or /prototypes/1.json
  def update
    respond_to do |format|
      if @prototype.update(prototype_params)
        format.html { redirect_to prototype_url(@prototype), notice: "Prototype was successfully updated." }
        format.json { render :show, status: :ok, location: @prototype }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prototype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prototypes/1 or /prototypes/1.json
  def destroy
    @prototype.destroy

    respond_to do |format|
      format.html { redirect_to prototypes_url, notice: "Prototype was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prototype
      @prototype = Prototype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prototype_params
      params.require(:prototype).permit(:name, :about)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adc2019Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="prototypes_<%= action_name %> <%= @prototype && @prototype.persisted? ? 'prototype_body_' + @prototype.id.to_s : '' %>">
    <%= yield %>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with(model: prototype) do |form| %>
  <% if prototype.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prototype.errors.count, "error") %> prohibited this prototype from being saved:</h2>

      <ul>
        <% prototype.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :about, style: "display: block" %>
    <%= form.text_area :about %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div id="<%= dom_id prototype %>">
  <p>
    <strong>Name:</strong>
    <%= prototype.name %>
  </p>

  <p>
    <strong>About:</strong>
    <%= prototype.about %>
  </p>

</div>

app/views/prototypes/edit.html.erb
<h1>Editing prototype</h1>

<%= render "form", prototype: @prototype %>

<br>

<div>
  <%= link_to "Show this prototype", @prototype %> |
  <%= link_to "Back to prototypes", prototypes_path %>
</div>

app/views/prototypes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Prototypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prototypes.each do |prototype| %>
      <tr>
        <td><%= prototype.name %></td>
        <td><%= prototype.about %></td>
        <td><%= link_to 'Show', prototype %></td>
        <td><%= link_to 'Edit', edit_prototype_path(prototype) %></td>
        <td><%= link_to 'Destroy', prototype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prototype', new_prototype_path %>

app/views/prototypes/new.html.erb
<h1>New prototype</h1>

<%= render "form", prototype: @prototype %>

<br>

<div>
  <%= link_to "Back to prototypes", prototypes_path %>
</div>

app/views/prototypes/show.html.erb
<%= javascript_pack_tag "prototype_#{@prototype.id}" %>
<div id="prototype_<%= @prototype.id %>"></div>